
server:
  port: 8088
  servlet:
    context-path: "/upms"

spring:
  datasource:
    url: jdbc:mysql://47.107.55.1:3306/upms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  redis:
    host: 47.107.55.1
  thymeleaf:
    cache: false

