
server:
  port: 8088
  servlet:
    context-path: "/workflow"

spring:
  datasource:
    url: jdbc:mysql://47.107.55.1:3306/workflow?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  thymeleaf:
    cache: false

