# server
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# spring
spring:
  profiles:
    active: "@profiles.active@"
  session:
    store-type: redis
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/views/
    suffix: .html
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/upms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    druid:
      initial-size: 2
      max-active: 10
      max-wait: 60000
      min-idle: 2
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379

# mybatis
mybatis:
  config-location: classpath:config/mybatis-config.xml

# logging
logging:
  level:
    my.upms.modules: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG
